apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - istio-eastwest-gateway-1.11.3-c1-p.yaml
  - expose-istiod.yaml
  - expose-services.yaml
  - istio-remote-secret-cluster2.yaml